[package]
name = "lending_platform"
version = "1.0.0"

[addresses]
LFPlatform = "53b15477263d715a2265847e2f0156dd97e24d2938723a10d4b0c2f55158e7cc"

[dev-addresses]

[dependencies]
AptosFramework = { local = "aptos-core-main/aptos-move/framework/aptos-framework" }
AptosTokenObjects = { local = "aptos-core-main/aptos-move/framework/aptos-token-objects" }

[dev-dependencies]
