[package]
name = "lending_platform"
version = "1.0.0"

[addresses]
LFPlatform="_"

[dev-addresses]

[dependencies]
AptosFramework = { local = "aptos-core-main/aptos-move/framework/aptos-framework" }
AptosTokenObjects = { local = "aptos-core-main/aptos-move/framework/aptos-token-objects" }

[dev-dependencies]
